spring:
  datasource:
    url: jdbc:mysql://localhost:3306/second_hand_trade?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    druid:
      filters: wall,stat
      filter:
        wall:
          enabled: true
          config:
            delete-allow: true
      stat-view-servlet:
        login-username: admin
        login-password: admin
        enabled: true
      reset-stat-enable: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  mapper-locations: classpath:mappers/*xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.sht.domain
server:
  port: 8081
upload:
  path: H:\study\upload\
  server:
    host: 'http://localhost:'
    port: 9090